### ISSUE TITLE
Multiple Vsync kills framerate.

### ISSUE THREAD

**Issue by cheako** [virtual-programming/witcher2-linux#125]
I'm using the i3 window manager with compton.

compton --backend glx --vsync opengl

Disabling vsync in Witcher 2 brings the framerate way up.  With this change Game is Playable at Ultra settings using DFSG approved video drivers(Mesa/DRI).

I'm unsure if it's possible for an application to discover if it's running under a compositor and if so how to probe the settings.  Idealy an X extension would allow a client to query these details.

Note for i3 users, the actual i3 config line.  Depends on daemon, another program.
exec --no-startup-id daemon -n compton -- compton --backend glx --vsync opengl

**Comment by vpltd-peterm** [comment]
This is a larger problem on Linux, and affects more titles than just ours. As such, we cannot really do anything about it.

**Comment by licaon-kter** [comment]
I'm also using i3 + compton but I don't see this with the closed source drivers on nVidia

My compton start line (might be nVidia specific though)
```
compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --config /dev/null --refresh-rate 60 --use-ewmh-active-win --glx-no-rebind-pixmap --glx-swap-method buffer-age --xrender-sync --xrender-sync-fence
```

**Comment by kakra** [comment]
Usually, compositors should suspend itself as soon as an application does proper fullscreen. In that way, an X extension already exists. Many applications don't really announce fullscreen but just place a borderless, fullscreen window, resized to the edge of the display. Maybe that's the problem here? The closed-source NVIDIA driver seems to have some counter-measures to detect those cases with regards to bypassing the compositor and vsync flags.
