### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by jenden0** [virtual-programming/witcher2-linux#156]
After recently installing my GoG version I tried to launch only to run in to an immediate crash.
After clicking launch from the launcher the screen goes black for a few seconds before coming back with the crash report dialog.  I submitted a couple copies of the crash, here's the text file for reference
[Crash Report Wed 25 Nov 2015 02:01:48 PM JST.txt](https://github.com/virtual-programming/witcher2-linux/files/43486/Crash.Report.Wed.25.Nov.2015.02.01.48.PM.JST.txt)

**Comment by eydee** [comment]
It seems that you have the same problem as the person posting something similar for Bioshock. Your nvidia driver reports some very low OpenGL version which isn't enough for the game. Update or downgrade your video driver, use whatever usually works in games that need OGL3/4.

**Comment by vpltd-peterm** [comment]
We'd need an actual crash report reference to look up the crash on our end. Due to the nature of Gentoo, it frequently causes binary incompatibility issues, though.

**Comment by kakra** [comment]
I mostly fixed those binaries incompatibilities by disabling the steam runtime and symlinking the few binaries that some games need sometimes to the steam runtime. Libasound e.g. seems to be horribly broken in steam runtime. Using the gentoo supplied libasound could fix most games. Apparently with some games it's vice versa: They only work with a steam supplied libasound. There're similar issues with libgnutls, libpcre and a few others.

For me, a look at dmesg and .xsession-errors to identify the broken library was enough most of the time, then I experimented with symlinking different versions of the library into the game directory until it worked. Lddtree is your friend here, helping identifying missing libs and incompatible versions. Keep an eye on 64bit vs 32bit libs.

Since you're using the GoG version, you don't have the steam runtime to try with. But I'm sure you can download it somewhere, then simply copy libs from the archive to the game directory to try things out.

You could also fiddle around with LDPATH and LD_PRELOAD but it's usually a bigger adventure then simply providing the correct libs within the game path - because it won't override all libs.

**Comment by jenden0** [comment]
Thanks, I'll try checking out the dmesg/.xsession-errors logs.  I've got
steam installed separately for other games, so I should be able to grab the
libraries from there.

Regarding the crash report reference, where can that be found?  I looked
around for it as I saw it requested in other bugs, but I never got any kind
of reference/confirmation after sending the crash report.

**Comment by jenden0** [comment]
This turned out to be a dupe of #149 (GoG version not working without manually merging the pack0.dzip file.
