### ISSUE TITLE
Intermittent stuttering in Beta 4

### ISSUE THREAD

**Issue by pierrep** [virtual-programming/witcher2-linux#49]
Tested the latest beta and while running around I get occasional stutters or pauses, that feel like buffering or loading. The 'stable' release doesn't suffer from this, even though the fps is lower. It doesn't seem to relate to the complexity of the scene either. I get around 30-60fps in the beta, and 20-35 in the original.

Also during loading, the screen sometimes turns black and stays like that for 3-4 seconds instead of going straight to the loading screens.

Ubuntu 14.04, Nvidia GTX660, 331.38 drivers

**Comment by vpltd-peterm** [comment]
Can people please advise if Beta 5 is better in this regard?
One thing that we have found helps immensely is nvidia's __GL_THREADED_OPTIMIZATIONS option. Enabling this helps a lot.

**Comment by pierrep** [comment]
Will do when I get a chance. Just curious, is there a way to programmatically turn on __GL_THREADED_OPTIMIZATIONS?

**Comment by vpltd-peterm** [comment]
It is an environment variable that needs to be set before you launch the game.
For Steam, edit the Launch options to read "__GL_THREADED_OPTIMIZATIONS=1 %command%"

**Comment by pierrep** [comment]
Yes I'm aware of that, was just wondering if it could be done programmatically...without resorting to a bash script for example.

**Comment by vpltd-peterm** [comment]
Currently there's no setting in the configurator for this, as it's driver specific, and needs to be set before the executable is run

**Comment by who-me** [comment]
Holy smokes, I did not even think to try that. I was already getting decent performance since your last patch. 40-60 fps but with threaded optimizations enabled for the nvidia driver this has now moved to 60-80 fps in the king's camp (at the start of the game)
 
I always thought that your optimizations and the nvidia threaded optimizations both did the same thing and, like in the wine + csmt case, having both enabled would actually mean worse performance. **I'm so glad I was wrong.**

Pictures or it did not happen, right :) Top images are w/o TO, bottom are with TO enabled: 
 
https://imgur.com/SKr9gPN,KtNwnv0#0
https://imgur.com/SKr9gPN,KtNwnv0#1

**Comment by vpltd-peterm** [comment]
The big problem is that we cannot actually do any multithreaded use of GL ourselves, as GL specifies a context can only be owned by one thread at a time. We initially tried having one context per thread, sharing each others resources, but it seemed this just caused horrendous driver stalls.

We're not 100% sure what nvidia's threaded optimisations do, but it looks like some tasks such as compiling shaders or uploading textures are deferred to a second thread, rather than just stalling our worker thread until complete.

Really, we need to see GL supporting multithreading natively - I think this is a good example of why that is!

**Comment by licaon-kter** [comment]
@vpltd-peterm: Can't you make the launcher check for nVidia ( pci id 10DE ) and pass the *__GL_THREADED_OPTIMIZATIONS=1* to the **witcher** executable?

**Comment by vpltd-peterm** [comment]
Perhaps. I am hesitant to do this as the behavior of __GL_THREADED_OPTIMIZATIONS could change between driver releases. I would prefer to find out more from Nvidia about what this option does, and at which points it will be improving our renderers behavior, before providing any "official" support for it.

**Comment by dubigrasu** [comment]
Valve is doing this anyway for (most of ) their games, regardless of the card used.
CS.GO for example: http://pastebin.com/M3vk5K8U

**Comment by pierrep** [comment]
"Really, we need to see GL supporting multithreading natively - I think this is a good example of why that is!"

Totally agree. Fingers crossed OpenGL Next will address this, and also give us precompiled GLSL shaders!

**Comment by pierrep** [comment]
OK finally got around to trying this again. Unfortunately I upgraded my motherboard from Ivy Bridge to a second generation Haswell, so I don't have the original testing environment. However I can say that my FPS is more stable, between 40-50fps. Turning on __GL_THREADED_OPTIMIZATIONS doesn't give me an fps boost, but it does seem to make the game run smoother (even less fps variations and barely noticeable hiccups).
I'm happy to close this, however while testing I did get this crash, not sure if it's steam client related or game related (looks like java): 
![witcher2-crash](https://cloud.githubusercontent.com/assets/392160/6441377/619abae8-c13b-11e4-8b25-68b58fa0a958.png)
